n1 = input('Digite algo: ')
print(type(n1))
print('É um número? ', n1.isnumeric())
print('É uma letra? ', n1.isalpha())
print('É um ascii?? ', n1.isascii())
print('É um decimal? ', n1.isdecimal())
print('É um digito? ', n1.isdigit())
print('Está em minúsculas? ', n1.islower())
print('Está em maiúsculas? ', n1.isupper())
print('É printável? ', n1.isprintable())
